// Famous people with their lifespan data
export interface FamousPerson {
  name: string;
  lifespanYears: number;
  knownFor: string;
}

export const famousPeople: FamousPerson[] = [
  { name: "Albert Einstein", lifespanYears: 76, knownFor: "Theory of Relativity" },
  { name: "Marie Curie", lifespanYears: 66, knownFor: "Pioneering research on radioactivity" },
  { name: "Leonardo da Vinci", lifespanYears: 67, knownFor: "Art and inventions in the Renaissance" },
  { name: "Wolfgang Amadeus Mozart", lifespanYears: 35, knownFor: "Classical music compositions" },
  { name: "Vincent Van Gogh", lifespanYears: 37, knownFor: "Post-impressionist paintings" },
  { name: "Jane Austen", lifespanYears: 41, knownFor: "Classic English literature" },
  { name: "Nikola Tesla", lifespanYears: 86, knownFor: "Electrical engineering innovations" },
  { name: "Elvis Presley", lifespanYears: 42, knownFor: "Rock and roll music" },
  { name: "Stephen Hawking", lifespanYears: 76, knownFor: "Theoretical physics and cosmology" },
  { name: "Marilyn Monroe", lifespanYears: 36, knownFor: "Iconic film roles and modeling" },
  { name: "Frida Kahlo", lifespanYears: 47, knownFor: "Surrealist painter" },
  { name: "William Shakespeare", lifespanYears: 52, knownFor: "Playwright and poet" },
  { name: "Ludwig van Beethoven", lifespanYears: 56, knownFor: "Classical music composer" },
  { name: "Rosa Parks", lifespanYears: 92, knownFor: "Civil rights activist" },
  { name: "Emily Dickinson", lifespanYears: 55, knownFor: "American poet" },
  { name: "Martin Luther King Jr.", lifespanYears: 39, knownFor: "Civil rights leader" },
  { name: "Agatha Christie", lifespanYears: 85, knownFor: "Mystery novelist" },
  { name: "Pablo Neruda", lifespanYears: 69, knownFor: "Poet and diplomat" },
  { name: "Ada Lovelace", lifespanYears: 36, knownFor: "First computer programmer" },
  { name: "Charles Darwin", lifespanYears: 73, knownFor: "Theory of evolution" },
  { name: "Virginia Woolf", lifespanYears: 59, knownFor: "Modernist author and feminist" },
  { name: "Sylvia Plath", lifespanYears: 30, knownFor: "Poet and novelist" },
  { name: "Louis Armstrong", lifespanYears: 69, knownFor: "Jazz musician" },
  { name: "Amelia Earhart", lifespanYears: 39, knownFor: "Aviation pioneer" },
  { name: "Abraham Lincoln", lifespanYears: 56, knownFor: "16th US President" },
  { name: "Audrey Hepburn", lifespanYears: 63, knownFor: "Actress and humanitarian" },
  { name: "Alexander Fleming", lifespanYears: 73, knownFor: "Discoverer of penicillin" },
  { name: "Billie Holiday", lifespanYears: 44, knownFor: "Jazz singer" },
  { name: "Ernest Hemingway", lifespanYears: 61, knownFor: "Novelist and short story writer" },
  { name: "Indira Gandhi", lifespanYears: 66, knownFor: "Prime Minister of India" },
  { name: "Jimi Hendrix", lifespanYears: 27, knownFor: "Rock guitarist" },
  { name: "Louis Pasteur", lifespanYears: 72, knownFor: "Microbiologist and chemist" },
  { name: "Joan of Arc", lifespanYears: 19, knownFor: "French heroine and military leader" },
  { name: "Ella Fitzgerald", lifespanYears: 79, knownFor: "Jazz vocalist" },
  { name: "Edith Piaf", lifespanYears: 47, knownFor: "French singer" },
  { name: "Anne Frank", lifespanYears: 15, knownFor: "Holocaust victim and diarist" },
  { name: "John Lennon", lifespanYears: 40, knownFor: "Musician and peace activist" },
  { name: "Fyodor Dostoevsky", lifespanYears: 59, knownFor: "Novelist and philosopher" },
  { name: "Nina Simone", lifespanYears: 70, knownFor: "Singer, songwriter, and civil rights activist" },
  { name: "Mahatma Gandhi", lifespanYears: 78, knownFor: "Indian independence leader" },
  { name: "Aretha Franklin", lifespanYears: 76, knownFor: "Queen of Soul" },
  { name: "Maria Montessori", lifespanYears: 81, knownFor: "Physician and educator" },
  { name: "Simone de Beauvoir", lifespanYears: 78, knownFor: "Writer and feminist" },
  { name: "Michael Jackson", lifespanYears: 50, knownFor: "King of Pop" },
  { name: "Eleanor Roosevelt", lifespanYears: 78, knownFor: "First Lady and diplomat" },
  { name: "Oscar Wilde", lifespanYears: 46, knownFor: "Writer and poet" },
  { name: "Freddie Mercury", lifespanYears: 45, knownFor: "Lead vocalist of Queen" },
  { name: "Marie Antoinette", lifespanYears: 37, knownFor: "Queen of France" },
  { name: "Andy Warhol", lifespanYears: 58, knownFor: "Pop artist" },
  { name: "Pyotr Tchaikovsky", lifespanYears: 53, knownFor: "Composer" },
  { name: "Walt Disney", lifespanYears: 65, knownFor: "Animation pioneer and entrepreneur" },
  { name: "Bob Marley", lifespanYears: 36, knownFor: "Reggae musician" },
  { name: "John F. Kennedy", lifespanYears: 46, knownFor: "35th US President" },
  { name: "Cleopatra", lifespanYears: 39, knownFor: "Last active ruler of Ptolemaic Egypt" },
  { name: "Bruce Lee", lifespanYears: 32, knownFor: "Martial artist and actor" },
  { name: "Miles Davis", lifespanYears: 65, knownFor: "Jazz musician" },
  { name: "Diane Arbus", lifespanYears: 48, knownFor: "Photographer" },
  { name: "Malcolm X", lifespanYears: 39, knownFor: "Human rights activist" },
  { name: "Amy Winehouse", lifespanYears: 27, knownFor: "Singer-songwriter" },
  { name: "René Descartes", lifespanYears: 53, knownFor: "Philosopher and mathematician" },
  { name: "David Bowie", lifespanYears: 69, knownFor: "Musician and actor" },
  { name: "Mary Shelley", lifespanYears: 53, knownFor: "Novelist who wrote Frankenstein" },
  { name: "Cesar Chavez", lifespanYears: 66, knownFor: "Labor leader and civil rights activist" },
  { name: "Alan Turing", lifespanYears: 41, knownFor: "Computer scientist and mathematician" },
  { name: "Robin Williams", lifespanYears: 63, knownFor: "Actor and comedian" },
  { name: "Rosalind Franklin", lifespanYears: 37, knownFor: "Chemist and X-ray crystallographer" },
  { name: "Tupac Shakur", lifespanYears: 25, knownFor: "Rapper and actor" },
  { name: "Sacagawea", lifespanYears: 25, knownFor: "Guide for the Lewis and Clark Expedition" },
  { name: "Kurt Cobain", lifespanYears: 27, knownFor: "Nirvana frontman" },
  { name: "Zora Neale Hurston", lifespanYears: 69, knownFor: "Writer and anthropologist" }
];

export const longLivedFamousPeople: FamousPerson[] = [
  { name: "Jeanne Calment", lifespanYears: 122, knownFor: "Oldest verified human in history" },
  { name: "Salvador Dalí", lifespanYears: 84, knownFor: "Surrealist painter" },
  { name: "Harriet Tubman", lifespanYears: 91, knownFor: "Abolitionist and political activist" },
  { name: "Frank Sinatra", lifespanYears: 82, knownFor: "Singer and actor" },
  { name: "Pablo Picasso", lifespanYears: 91, knownFor: "Revolutionary artist" },
  { name: "Thomas Edison", lifespanYears: 84, knownFor: "Inventor and businessman" },
  { name: "Coco Chanel", lifespanYears: 87, knownFor: "Fashion designer" },
  { name: "Sojourner Truth", lifespanYears: 86, knownFor: "Abolitionist and women's rights activist" },
  { name: "Shirley Temple", lifespanYears: 85, knownFor: "Child actress and diplomat" },
  { name: "Florence Nightingale", lifespanYears: 90, knownFor: "Founder of modern nursing" },
  { name: "Charlie Chaplin", lifespanYears: 88, knownFor: "Silent film actor and director" },
  { name: "Georgia O'Keeffe", lifespanYears: 98, knownFor: "American modernist artist" },
  { name: "Mohandas Gandhi", lifespanYears: 78, knownFor: "Indian independence leader" },
  { name: "Galileo Galilei", lifespanYears: 77, knownFor: "Astronomer and physicist" },
  { name: "Maya Angelou", lifespanYears: 86, knownFor: "Poet and civil rights activist" },
  { name: "Sigmund Freud", lifespanYears: 83, knownFor: "Founder of psychoanalysis" },
  { name: "Margaret Thatcher", lifespanYears: 87, knownFor: "First female British Prime Minister" },
  { name: "Isaac Newton", lifespanYears: 84, knownFor: "Laws of motion and gravitation" },
  { name: "Michelangelo", lifespanYears: 88, knownFor: "Renaissance artist" },
  { name: "Toni Morrison", lifespanYears: 88, knownFor: "Novelist and Nobel Prize winner" },
  { name: "Alfred Hitchcock", lifespanYears: 80, knownFor: "Film director" },
  { name: "Greta Garbo", lifespanYears: 84, knownFor: "Hollywood actress" },
  { name: "Hedy Lamarr", lifespanYears: 85, knownFor: "Actress and inventor" },
  { name: "Nelson Mandela", lifespanYears: 95, knownFor: "Anti-apartheid revolutionary and president" },
  { name: "Julia Child", lifespanYears: 91, knownFor: "Chef and television personality" },
  { name: "Ruth Bader Ginsburg", lifespanYears: 87, knownFor: "US Supreme Court Justice" },
  { name: "Katherine Johnson", lifespanYears: 101, knownFor: "NASA mathematician" },
  { name: "Gandhi", lifespanYears: 78, knownFor: "Leading India to independence" },
  { name: "Winston Churchill", lifespanYears: 90, knownFor: "British Prime Minister during WWII" },
  { name: "Pablo Picasso", lifespanYears: 91, knownFor: "Revolutionary artist" },
  { name: "Queen Elizabeth II", lifespanYears: 96, knownFor: "Britain's longest-reigning monarch" },
  { name: "Nelson Mandela", lifespanYears: 95, knownFor: "Anti-apartheid revolutionary and president" },
  { name: "Betty White", lifespanYears: 99, knownFor: "Beloved actress and comedian" },
  { name: "Kirk Douglas", lifespanYears: 103, knownFor: "Golden Age of Hollywood actor" },
  { name: "George Burns", lifespanYears: 100, knownFor: "Comedian with a century-long career" },
  { name: "Olivia de Havilland", lifespanYears: 104, knownFor: "Classic Hollywood actress" },
  { name: "Katherine Johnson", lifespanYears: 101, knownFor: "NASA mathematician" },
  { name: "David Rockefeller", lifespanYears: 101, knownFor: "American banker and philanthropist" },
  { name: "Tao Porchon-Lynch", lifespanYears: 101, knownFor: "Yoga master and competitive dancer" },
  { name: "Irving Berlin", lifespanYears: 101, knownFor: "Composer and lyricist" },
  { name: "Michio Suzuki", lifespanYears: 101, knownFor: "Japanese industrialist and founder of Suzuki" },
  { name: "Herman Wouk", lifespanYears: 103, knownFor: "Pulitzer Prize-winning author" },
  { name: "Luise Rainer", lifespanYears: 104, knownFor: "First actress to win consecutive Oscars" },
  { name: "Rosa Parks", lifespanYears: 92, knownFor: "Civil rights activist" },
  { name: "Beverly Cleary", lifespanYears: 104, knownFor: "Children's author" },
  { name: "Norman Lloyd", lifespanYears: 106, knownFor: "Actor, director, and producer" },
  { name: "Lisel Heise", lifespanYears: 100, knownFor: "Political activist who joined politics at 100" },
  { name: "Zsa Zsa Gabor", lifespanYears: 99, knownFor: "Hungarian-American actress and socialite" },
  { name: "Bob Hope", lifespanYears: 100, knownFor: "Entertainer and comedian" },
  { name: "Diahann Carroll", lifespanYears: 84, knownFor: "Actress and singer" },
  { name: "John Glenn", lifespanYears: 95, knownFor: "Astronaut and U.S. Senator" },
  { name: "Gloria Stuart", lifespanYears: 100, knownFor: "Actress from Titanic" },
  { name: "Harry Bernstein", lifespanYears: 101, knownFor: "Author who published his first book at 96" },
  { name: "Eileen Nearne", lifespanYears: 89, knownFor: "British spy during World War II" },
  { name: "Sidney Poitier", lifespanYears: 94, knownFor: "First Black actor to win Best Actor Oscar" },
  // { name: "Sister Madonna Buder", lifespanYears: 94, knownFor: "'Iron Nun' athlete" },
  { name: "I.M. Pei", lifespanYears: 102, knownFor: "Architect who designed the Louvre Pyramid" },
  { name: "Mary Soames", lifespanYears: 91, knownFor: "Writer and daughter of Winston Churchill" },
  { name: "Christopher Plummer", lifespanYears: 91, knownFor: "Actor" },
  { name: "Judith Kerr", lifespanYears: 95, knownFor: "Author and illustrator" },
  { name: "Jimmy Carter", lifespanYears: 100, knownFor: "39th US President and humanitarian" },
  // { name: "Eva Marie Saint", lifespanYears: 99, knownFor: "Academy Award-winning actress" },
  { name: "B.B. King", lifespanYears: 89, knownFor: "Blues musician" },
  // { name: "Judi Dench", lifespanYears: 90, knownFor: "Award-winning actress" },
  // { name: "Willie Nelson", lifespanYears: 91, knownFor: "Country music artist" },
  { name: "Iris Apfel", lifespanYears: 102, knownFor: "Fashion icon and interior designer" },
  { name: "Sidney Sheldon", lifespanYears: 89, knownFor: "Writer and producer" },
  { name: "Harriette Thompson", lifespanYears: 94, knownFor: "Oldest woman to complete a marathon" },
  { name: "Stan Lee", lifespanYears: 95, knownFor: "Comic book writer and publisher" },
  { name: "Julia Child", lifespanYears: 91, knownFor: "Chef and TV personality" },
  { name: "Georgia O'Keeffe", lifespanYears: 98, knownFor: "American modernist artist" },
  // { name: "Dick Van Dyke", lifespanYears: 98, knownFor: "Actor and entertainer" },
  { name: "Doris Day", lifespanYears: 97, knownFor: "Actress and singer" },
  { name: "Harry Patch", lifespanYears: 111, knownFor: "Last surviving combat veteran of WWI" },
  // { name: "Fauja Singh", lifespanYears: 114, knownFor: "Centenarian marathon runner" }
];
